CREATE SEQUENCE FLOWERSTOCK_SEQ;

CREATE TABLE FLOWERSTOCK
(	ID NUMBER  primary key,
	COUNT  NUMBER NOT NULL,
   );
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,100);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,150);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,200);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,250);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,300);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,40);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,230);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,100);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,200);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,300);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,400);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,50);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,70);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,140);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,200);
commit ;