CREATE SEQUENCE FLOWERSTOCK_SEQ;

CREATE TABLE FLOWERSTOCK
(	ID NUMBER  NOT NULL,
	FLOWER_ID number  PRIMARY KEY,
	COUNT  NUMBER NOT NULL,
	foreign key (FlOWER_ID) references Flower(id)

--	CONSTRAINT FLOWERSTOCK_FLWR_FK1 FOREIGN KEY ID REFERENCES FLOWER ID
   );
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,100,100);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,101,150);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,102,200);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,103,250);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,104,300);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,105,40);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,106,230);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,107,100);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,108,200);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,109,300);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,110,400);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,111,50);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,112,70);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,113,140);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,114,200);
commit ;