CREATE SEQUENCE FLOWERSTOCK_SEQ;

CREATE TABLE FLOWERSTOCK
(	ID NUMBER  PRIMARY KEY,
	FLOWER_ID number  NOT NULL,
	COUNT  NUMBER NOT NULL,
	foreign key (id) references Flower(id)

--	CONSTRAINT FLOWERSTOCK_FLWR_FK1 FOREIGN KEY ID REFERENCES FLOWER ID
   );
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,1,100);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,2,150);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,3,200);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,4,250);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,5,300);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,6,40);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,7,230);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,8,100);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,9,200);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,10,300);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,11,400);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,12,50);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,13,70);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,14,140);
 INSERT INTO FLOWERSTOCK VALUES(FLOWERSTOCK_SEQ.NEXTVAL,15,200);
commit ;