CREATE SEQUENCE BUCKET_SEQ;

CREATE TABLE BUCKET(
ID NUMBER PRIMARY KEY,
ORDERS_ID NUMBER NOT NULL,
FLOWER_ID NUMBER NOT NULL,
AMOUNT NUMBER NOT NULL,
PRICE DECIMAL NOT NULL,
FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS(ID),
FOREIGN KEY(FLOWER_ID) REFERENCES FLOWER(ID)
)