CREATE SEQUENCE BUCKET_SEQ;

CREATE TABLE BUCKET(
ID NUMBER PRIMARY KEY,
ORDERS_ID NUMBER NOT NULL,
USER_ID VARCHAR NOT NULL,
FLOWER_COUNT NUMBER NOT NULL,
PRICE DECIMAL NOT NULL,
FOREIGN KEY (ORDERS_ID)REFERENCES ORDERS(ID)
)